# Metadata syntax: <https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions>

name: Fetch the secret from doppler.com
description: This action allows receiving the secret from doppler.com

inputs:
  token:
    description: Doppler service token # docs: <https://docs.doppler.com/docs/enclave-service-tokens>
    required: true
  project:
    description: Doppler project name # docs: <https://docs.doppler.com/docs/enclave-project-setup>
    required: true
  config:
    description: Doppler config (also known as "environment") # docs: <https://docs.doppler.com/docs/enclave-root-configs>
    required: false
    default: prd
  secret-name:
    description: Secret name
    required: true
  save-to-file:
    description: Path to the file for storing the secret (in this case action output named "secret" will be empty)
    required: false

outputs:
  secret:
    description: Secret value

runs:
  using: node16
  main: dist/index.js

branding:
  icon: activity
  color: yellow
